# Generated by Django 2.1.5 on 2019-03-21 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remiljscrumy', '0002_scrumuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='scrumuser',
            name='role',
        ),
        migrations.AddField(
            model_name='scrumprojectrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remiljscrumy.ScrumUser'),
        ),
    ]
