# Generated by Django 2.1.5 on 2019-03-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiljscrumy', '0003_auto_20190321_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='moveable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
