# Generated by Django 2.1.5 on 2019-03-29 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remiljscrumy', '0005_auto_20190329_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumuser',
            options={'ordering': ['nickname'], 'verbose_name_plural': 'Scrum User'},
        ),
        migrations.AlterModelOptions(
            name='scrumygoals',
            options={'ordering': ['-goal_id'], 'verbose_name_plural': 'Scrumy Goals'},
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remiljscrumy.ScrumUser'),
        ),
    ]
