# Generated by Django 2.1.5 on 2019-04-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiljscrumy', '0006_auto_20190329_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumygoals',
            options={'ordering': ['goal_id'], 'verbose_name_plural': 'Scrumy Goals'},
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_id',
            field=models.IntegerField(),
        ),
    ]
