# Generated by Django 2.1.5 on 2019-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiljscrumy', '0008_auto_20190404_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
