# Generated by Django 2.1.5 on 2019-04-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remiljscrumy', '0009_auto_20190408_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumygoals',
            name='status',
        ),
    ]
